### PR TITLE
LPS-69775 Fix test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@diogo-lins Please forward to @vicnate5 when you finish. Thanks !!!

@vicnate5 Could you add a Poshi test for this one ? You can forward to Brian when you're done. Thanks !!! 

cc @marcellustavares

**Comment by marcellustavares** [comment]
@leoadb, could you please create a separate LPS so we can handle the validation for this field type?

**Comment by leoadb** [comment]
@marcellustavares Sure. Do you mean add the feature we talked about to ValueAccessor class, right ?

**Comment by diogo-lins** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diogo-lins** [comment]
Pushed to https://github.com/brunobasto/liferay-portal/pull/816

**Pull request closed without merging**
